window.esdocSearchIndex = [
  [
    "spatial-navigation-cursor~cursormanager",
    "class/spatial-navigation-cursor/index.js~CursorManager.html",
    "<span>CursorManager</span> <span class=\"search-result-import-path\">spatial-navigation-cursor</span>",
    "class"
  ],
  [
    "",
    "test-file/spatial-navigation-cursor/index.test.js.html#lineNumber17",
    "cursor",
    "test"
  ],
  [
    "spatial-navigation-cursor/index.js",
    "file/spatial-navigation-cursor/index.js.html",
    "spatial-navigation-cursor/index.js",
    "file"
  ],
  [
    "spatial-navigation-cursor/index.js~cursormanager#appendtoroot_",
    "class/spatial-navigation-cursor/index.js~CursorManager.html#instance-method-appendToRoot_",
    "spatial-navigation-cursor/index.js~CursorManager#appendToRoot_",
    "method"
  ],
  [
    "spatial-navigation-cursor/index.js~cursormanager#constructor",
    "class/spatial-navigation-cursor/index.js~CursorManager.html#instance-constructor-constructor",
    "spatial-navigation-cursor/index.js~CursorManager#constructor",
    "method"
  ],
  [
    "spatial-navigation-cursor/index.js~cursormanager#cursor_",
    "class/spatial-navigation-cursor/index.js~CursorManager.html#instance-member-cursor_",
    "spatial-navigation-cursor/index.js~CursorManager#cursor_",
    "member"
  ],
  [
    "spatial-navigation-cursor/index.js~cursormanager#focusselector_",
    "class/spatial-navigation-cursor/index.js~CursorManager.html#instance-member-focusSelector_",
    "spatial-navigation-cursor/index.js~CursorManager#focusSelector_",
    "member"
  ],
  [
    "spatial-navigation-cursor/index.js~cursormanager#getcursor",
    "class/spatial-navigation-cursor/index.js~CursorManager.html#instance-method-getCursor",
    "spatial-navigation-cursor/index.js~CursorManager#getCursor",
    "method"
  ],
  [
    "spatial-navigation-cursor/index.js~cursormanager#hidecursor_",
    "class/spatial-navigation-cursor/index.js~CursorManager.html#instance-method-hideCursor_",
    "spatial-navigation-cursor/index.js~CursorManager#hideCursor_",
    "method"
  ],
  [
    "spatial-navigation-cursor/index.js~cursormanager#move",
    "class/spatial-navigation-cursor/index.js~CursorManager.html#instance-method-move",
    "spatial-navigation-cursor/index.js~CursorManager#move",
    "method"
  ],
  [
    "spatial-navigation-cursor/index.js~cursormanager#movecursorto_",
    "class/spatial-navigation-cursor/index.js~CursorManager.html#instance-method-moveCursorTo_",
    "spatial-navigation-cursor/index.js~CursorManager#moveCursorTo_",
    "method"
  ],
  [
    "spatial-navigation-cursor/index.js~cursormanager#root_",
    "class/spatial-navigation-cursor/index.js~CursorManager.html#instance-member-root_",
    "spatial-navigation-cursor/index.js~CursorManager#root_",
    "member"
  ],
  [
    "spatial-navigation-cursor/index.js~cursormanager#scrollintoview_",
    "class/spatial-navigation-cursor/index.js~CursorManager.html#instance-method-scrollIntoView_",
    "spatial-navigation-cursor/index.js~CursorManager#scrollIntoView_",
    "method"
  ],
  [
    "spatial-navigation-cursor/index.js~cursormanager#showcursor_",
    "class/spatial-navigation-cursor/index.js~CursorManager.html#instance-method-showCursor_",
    "spatial-navigation-cursor/index.js~CursorManager#showCursor_",
    "method"
  ],
  [
    "spatial-navigation-cursor/index.js~cursormanager#stylecursor_",
    "class/spatial-navigation-cursor/index.js~CursorManager.html#instance-method-styleCursor_",
    "spatial-navigation-cursor/index.js~CursorManager#styleCursor_",
    "method"
  ],
  [
    "spatial-navigation-cursor/index.js~cursormanager#viewheight_",
    "class/spatial-navigation-cursor/index.js~CursorManager.html#instance-member-viewHeight_",
    "spatial-navigation-cursor/index.js~CursorManager#viewHeight_",
    "member"
  ],
  [
    "spatial-navigation-cursor/index.test.js",
    "test-file/spatial-navigation-cursor/index.test.js.html",
    "spatial-navigation-cursor/index.test.js",
    "testFile"
  ]
]