window.esdocSearchIndex = [
  [
    "spatial-navigation-cursor~cursormanager",
    "class/spatial-navigation-cursor/index.js~CursorManager.html",
    "<span>CursorManager</span> <span class=\"search-result-import-path\">spatial-navigation-cursor</span>",
    "class"
  ],
  [
    "",
    "test-file/spatial-navigation-cursor/index.test.js.html#lineNumber26",
    "cursor",
    "test"
  ],
  [
    "spatial-navigation-cursor/index.js",
    "file/spatial-navigation-cursor/index.js.html",
    "spatial-navigation-cursor/index.js",
    "file"
  ],
  [
    "spatial-navigation-cursor/index.js~cursormanager#appendtoroot_",
    "class/spatial-navigation-cursor/index.js~CursorManager.html#instance-method-appendToRoot_",
    "spatial-navigation-cursor/index.js~CursorManager#appendToRoot_",
    "method"
  ],
  [
    "spatial-navigation-cursor/index.js~cursormanager#constructor",
    "class/spatial-navigation-cursor/index.js~CursorManager.html#instance-constructor-constructor",
    "spatial-navigation-cursor/index.js~CursorManager#constructor",
    "method"
  ],
  [
    "spatial-navigation-cursor/index.js~cursormanager#cursor_",
    "class/spatial-navigation-cursor/index.js~CursorManager.html#instance-member-cursor_",
    "spatial-navigation-cursor/index.js~CursorManager#cursor_",
    "member"
  ],
  [
    "spatial-navigation-cursor/index.js~cursormanager#disconnectfocus_",
    "class/spatial-navigation-cursor/index.js~CursorManager.html#instance-method-disconnectFocus_",
    "spatial-navigation-cursor/index.js~CursorManager#disconnectFocus_",
    "method"
  ],
  [
    "spatial-navigation-cursor/index.js~cursormanager#focus",
    "class/spatial-navigation-cursor/index.js~CursorManager.html#instance-method-focus",
    "spatial-navigation-cursor/index.js~CursorManager#focus",
    "method"
  ],
  [
    "spatial-navigation-cursor/index.js~cursormanager#focusclassname_",
    "class/spatial-navigation-cursor/index.js~CursorManager.html#instance-member-focusClassName_",
    "spatial-navigation-cursor/index.js~CursorManager#focusClassName_",
    "member"
  ],
  [
    "spatial-navigation-cursor/index.js~cursormanager#focused_",
    "class/spatial-navigation-cursor/index.js~CursorManager.html#instance-member-focused_",
    "spatial-navigation-cursor/index.js~CursorManager#focused_",
    "member"
  ],
  [
    "spatial-navigation-cursor/index.js~cursormanager#getcursor",
    "class/spatial-navigation-cursor/index.js~CursorManager.html#instance-method-getCursor",
    "spatial-navigation-cursor/index.js~CursorManager#getCursor",
    "method"
  ],
  [
    "spatial-navigation-cursor/index.js~cursormanager#hidecursor_",
    "class/spatial-navigation-cursor/index.js~CursorManager.html#instance-method-hideCursor_",
    "spatial-navigation-cursor/index.js~CursorManager#hideCursor_",
    "method"
  ],
  [
    "spatial-navigation-cursor/index.js~cursormanager#move",
    "class/spatial-navigation-cursor/index.js~CursorManager.html#instance-method-move",
    "spatial-navigation-cursor/index.js~CursorManager#move",
    "method"
  ],
  [
    "spatial-navigation-cursor/index.js~cursormanager#movecursorto_",
    "class/spatial-navigation-cursor/index.js~CursorManager.html#instance-method-moveCursorTo_",
    "spatial-navigation-cursor/index.js~CursorManager#moveCursorTo_",
    "method"
  ],
  [
    "spatial-navigation-cursor/index.js~cursormanager#observefocus_",
    "class/spatial-navigation-cursor/index.js~CursorManager.html#instance-method-observeFocus_",
    "spatial-navigation-cursor/index.js~CursorManager#observeFocus_",
    "method"
  ],
  [
    "spatial-navigation-cursor/index.js~cursormanager#observer_",
    "class/spatial-navigation-cursor/index.js~CursorManager.html#instance-member-observer_",
    "spatial-navigation-cursor/index.js~CursorManager#observer_",
    "member"
  ],
  [
    "spatial-navigation-cursor/index.js~cursormanager#place",
    "class/spatial-navigation-cursor/index.js~CursorManager.html#instance-method-place",
    "spatial-navigation-cursor/index.js~CursorManager#place",
    "method"
  ],
  [
    "spatial-navigation-cursor/index.js~cursormanager#removefromroot_",
    "class/spatial-navigation-cursor/index.js~CursorManager.html#instance-method-removeFromRoot_",
    "spatial-navigation-cursor/index.js~CursorManager#removeFromRoot_",
    "method"
  ],
  [
    "spatial-navigation-cursor/index.js~cursormanager#resizecursorto_",
    "class/spatial-navigation-cursor/index.js~CursorManager.html#instance-method-resizeCursorTo_",
    "spatial-navigation-cursor/index.js~CursorManager#resizeCursorTo_",
    "method"
  ],
  [
    "spatial-navigation-cursor/index.js~cursormanager#root_",
    "class/spatial-navigation-cursor/index.js~CursorManager.html#instance-member-root_",
    "spatial-navigation-cursor/index.js~CursorManager#root_",
    "member"
  ],
  [
    "spatial-navigation-cursor/index.js~cursormanager#scrollintoview_",
    "class/spatial-navigation-cursor/index.js~CursorManager.html#instance-method-scrollIntoView_",
    "spatial-navigation-cursor/index.js~CursorManager#scrollIntoView_",
    "method"
  ],
  [
    "spatial-navigation-cursor/index.js~cursormanager#showcursor_",
    "class/spatial-navigation-cursor/index.js~CursorManager.html#instance-method-showCursor_",
    "spatial-navigation-cursor/index.js~CursorManager#showCursor_",
    "method"
  ],
  [
    "spatial-navigation-cursor/index.js~cursormanager#start",
    "class/spatial-navigation-cursor/index.js~CursorManager.html#instance-method-start",
    "spatial-navigation-cursor/index.js~CursorManager#start",
    "method"
  ],
  [
    "spatial-navigation-cursor/index.js~cursormanager#stop",
    "class/spatial-navigation-cursor/index.js~CursorManager.html#instance-method-stop",
    "spatial-navigation-cursor/index.js~CursorManager#stop",
    "method"
  ],
  [
    "spatial-navigation-cursor/index.js~cursormanager#stylecursor_",
    "class/spatial-navigation-cursor/index.js~CursorManager.html#instance-method-styleCursor_",
    "spatial-navigation-cursor/index.js~CursorManager#styleCursor_",
    "method"
  ],
  [
    "spatial-navigation-cursor/index.js~cursormanager#viewheight_",
    "class/spatial-navigation-cursor/index.js~CursorManager.html#instance-member-viewHeight_",
    "spatial-navigation-cursor/index.js~CursorManager#viewHeight_",
    "member"
  ],
  [
    "spatial-navigation-cursor/index.test.js",
    "test-file/spatial-navigation-cursor/index.test.js.html",
    "spatial-navigation-cursor/index.test.js",
    "testFile"
  ]
]